BIDS_dataset: FragilityEEGDataset
BIDS_sessions: ~
BIDS_runs:
- ses-presurgery/ieeg/sub-jh103_ses-presurgery_task-ictal_acq-ecog_run-01
- ses-presurgery/ieeg/sub-jh103_ses-presurgery_task-ictal_acq-ecog_run-02
- ses-presurgery/ieeg/sub-jh103_ses-presurgery_task-ictal_acq-ecog_run-03
backup: no
BIDS_subject: sub-jh103
overwrite: no
