smooth_erp: 2.0
analysis_frequency: 2.0
analysis_time: 0.0
erp_baseline:
- -1.0
- 0.0
erp_analysiswindow:
- 0.0
- 1.0
analyze_electrodes: 14-16
erp_downsample_rate_to: 100.0
condition_groups:
- group_name: A
  group_conditions:
  - known_a
  - last_a
  - drive_a
  - meant_a
- group_name: B
  group_conditions:
  - known_v
  - last_v
  - drive_v
  - meant_v
reference_name: default
epoch_choice__trial_ends: 2
epoch_choice__trial_starts: -1
epoch_choice: YABaOutlier
loaded_electrodes: 13-16,24
subject_code: YAB
project_name: demo
