'n': 100
pch: 16
col: steelblue
condition: sz5
reference_name: car
time_window:
- 0.0
- 20.0
load_electrodes: 13-62,64-76
epoch_file_name: subHUP070_seizure
subject_code: subHUP070
project_name: Retrostudy
