controllers: []
data_source: Uploads
data_source_pipeline: power_explorer/power_explorer-22_09_03-22_54_46
data_source_pipeline_target: omnibus_results
data_source_project: demo
main_camera:
  position:
  - 500.0
  - 0.0
  - 0.0
  up:
  - 0.0
  - 0.0
  - 1.0
  zoom: 1.0
project_name: '[Auto]'
shiny_outputId: custom_3d_viewer-viewer_ready
subject_code: DemoSubject
surface_types: ~
use_template: no
uploaded_source: electrode_value.fst
