SOZ_elec: '0'
resect_elec: '0'
plot_resect_elec: no
analysis_time_frequencies:
  '1':
    frequency_range:
    - 13
    - 30
    frequency_preset_delta: 0
    frequency_preset_theta: 0
    frequency_preset_alpha: 0
    frequency_preset_beta: 0
    frequency_preset_gamma: 0
    frequency_preset_high_gamma: 0
    time_range:
    - 0
    - 20
condition: 30s before sz1 (1)
reference: common_average
window_params:
- 2.5
- 0.5
frequency_range:
- 0
- 250
num_tapers: ~
min_nfft: 0
weighting: unity
detrend_opt: linear
parallel: yes
num_workers: 31.0
plot_on: no
verbose: no
xyflip: no
time_bandwidth: 3
time_window:
- 0
- 20
reference_name: Common_Average_Reference
load_electrodes: 1-4,7-24,26-36,42-43,46-54,56-69,72-95
selected_electrode: 1
epoch_file_name: subpt01_seizure
project_name: Retrostudy2
soz_electrodes: ''
resect_electrodes: ''
heatmap_name_type: number
ordered: yes
subject_code: subpt01
epoch_name: sz1 (2)
electrodes: 1-4,7-36,42-43,46-69,72-95
time_windows:
- 0
- 20
time_stat_end: 10.0
time_stat_start: 0.0
analysis_windows:
  '1':
    frequency_range:
    - 13.0
    - 31.0
    time_range:
    - 0.0
    - 20.0
plot_SOZ_elec: no
label: numeric
organize_top: no
text_size: 5.0
ML_time_range:
- 0
- 20
decibal: no
baseline: 30s before sz1 (1)
scale: None
baselined: no
start_time_baseline: 0.0
end_time_baseline: 0
