plot_resect_elec: no
resect_elec: '0'
text_size: 5.0
analysis_windows:
  '1':
    frequency_range:
    - 13.0
    - 31.0
    time_range:
    - -30.0
    - 30.0
organize_top: no
label: numeric
subject_code: subHUP064
project_name: Retrostudy
epoch_file_name: subHUP064_seizure
plot_SOZ_elec: no
SOZ_elec: '0'
load_electrodes: 3-88
reference_name: common_average
time_window:
- -30
- 30
time_bandwidth: 3.0
xyflip: no
verbose: no
plot_on: no
num_workers: 31.0
parallel: yes
detrend_opt: linear
weighting: unity
min_nfft: 0.0
num_tapers: 5.0
frequency_range:
- 0.5
- 256.0
window_params:
- 2.5
- 0.5
type: power
intervals:
- - -1.0
  - 2.0
reference: default
save_pipeline: yes
condition: sz1 (4)
time_stat_start: 0.0
time_stat_end: 10.0
threshold_type: zscore
threshold_level: 2.0
normalize: yes
