time_stat_end: 10.0
time_windows:
- -10.0
- 10.0
electrodes: 3,4-87
epoch_name: subHUP064_seizure
subject_code: subpt11
ordered: yes
heatmap_name_type: number
resect_electrodes: ''
soz_electrodes: ''
project_name: Retrostudy
epoch_file_name: subpt11_seizure
load_electrodes: 1-4,7-9,12-19,21-35,37,39-40,43-74,117-128
reference_name: car
time_window:
- -10
- 60
time_bandwidth: 3
xyflip: no
verbose: no
plot_on: no
num_workers: 31.0
parallel: yes
detrend_opt: linear
weighting: unity
min_nfft: 0
num_tapers: ~
frequency_range:
- 0
- 250
window_params:
- 2.5
- 0.5
reference: common_average
condition: sz1 (2)
analysis_time_frequencies:
  '1':
    frequency_range:
    - 13
    - 30
    frequency_preset_delta: 14
    frequency_preset_theta: 12
    frequency_preset_alpha: 12
    frequency_preset_beta: 26
    frequency_preset_gamma: 24
    frequency_preset_high_gamma: 10
    time_range:
    - 30
    - 40
plot_resect_elec: no
resect_elec: '0'
SOZ_elec: '0'
baseline: 30s before sz1 (1)
text_size: 5.0
organize_top: no
label: numeric
plot_SOZ_elec: no
analysis_windows:
  '1':
    frequency_range:
    - 13.0
    - 31.0
    time_range:
    - 0.0
    - 10.0
time_stat_start: 0.0
end_time_baseline: 30
start_time_baseline: 0
baselined: yes
scale: None
