analysis_time_frequencies:
  '1':
    frequency_range:
    - 3
    - 200
    time_range:
    - -1
    - 2
condition: sz (1)
reference: default
window_params:
- 0.2
- 0.01
frequency_range:
- 1
- 200
num_tapers: ~
min_nfft: 0
weighting: unity
detrend_opt: linear
parallel: yes
num_workers: 7.0
plot_on: no
verbose: no
xyflip: no
time_bandwidth: 3
time_window:
- -1
- 2
reference_name: noref
load_electrodes: 13-16,24,100-102
epoch_file_name: auditory_onset
project_name: demo
subject_code: DemoSubject
soz_electrodes: 3
heatmap_name_type: number
