condition: sz1 (4)
save_pipeline: yes
reference: default
intervals:
- - -1.0
  - 2.0
type: power
window_params:
- 2.0
- 0.5
frequency_range:
- 1
- 200
num_tapers: ~
min_nfft: 0
weighting: unity
detrend_opt: linear
parallel: yes
num_workers: 31.0
plot_on: no
verbose: no
xyflip: no
time_bandwidth: 3
time_window:
- -20
- 20
reference_name: bipolar
load_electrodes: 3-87
SOZ_elec: '0'
plot_SOZ_elec: no
epoch_file_name: subHUP064_seizure
project_name: fingerprinting
subject_code: subHUP064
label: names
organize_top: no
analysis_windows:
  '1':
    frequency_range:
    - 8.4
    - 35.7
    time_range:
    - -20
    - 20
text_size: 5
resect_elec: '0'
plot_resect_elec: no
