analysis_time_frequencies:
  '1':
    frequency_range:
    - 0.5
    - 4.0
    time_range:
    - 0.0
    - 20.0
analysis_windows:
  '1':
    frequency_range:
    - 13.0
    - 31.0
    time_range:
    - 0.0
    - 20.0
baseline: 30s before sz1 (1)
baselined: yes
condition: sz1 (2)
decibal: no
detrend_opt: linear
electrodes: 1-4,7-36,42-43,46-69,72-95
end_time_baseline: 10
epoch_choice__trial_ends: 10
epoch_choice__trial_starts: -5
epoch_file_name: subpt01_seizure
epoch_name: sz1 (2)
frequency_range:
- 0.5
- 150.0
heatmap_name_type: number
label: numeric
load_electrodes: 1-4,7-36,42-43,46-69,72-95
min_nfft: 0
ML_time_range:
- 0
- 20
num_tapers: ~
num_workers: 31.0
ordered: yes
organize_top: no
parallel: yes
plot_on: no
plot_resect_elec: no
plot_SOZ_elec: no
project_name: Retrostudy
reference: common_average
reference_name: car
resect_elec: '0'
resect_electrodes: ''
save_path: /Volumes/bigbrain/scripts/sean/stats/updated_plots/
scale: None
selected_electrode: 1
show_ML: no
SOZ_elec: '0'
soz_electrodes: ''
start_time_baseline: 0.0
subject_code: subpt01
text_size: 5.0
time_bandwidth: 3.0
time_stat_end: 10.0
time_stat_start: 0.0
time_window:
- 0.0
- 20.0
time_windows:
- 0
- 20
verbose: no
weighting: unity
window_params:
- 2.5
- 0.5
xyflip: no
