ordered: yes
heatmap_name_type: number
resect_electrodes: 30-40
soz_electrodes: 1-30
subject_code: subHUP064
project_name: Retrostudy
epoch_file_name: subHUP064_seizure
load_electrodes: 3-88
reference_name: common_average
time_window:
- -20
- 20
time_bandwidth: 3
xyflip: no
verbose: no
plot_on: no
num_workers: 31.0
parallel: yes
detrend_opt: linear
weighting: unity
min_nfft: 0
num_tapers: ~
frequency_range:
- 1
- 200
window_params:
- 2.5
- 0.5
reference: default
condition: sz (1)
analysis_time_frequencies:
  '1':
    frequency_range:
    - 15
    - 30
    time_range:
    - -20
    - 20
  '2':
    frequency_range:
    - 90
    - 200
    time_range:
    - -20
    - 20
  '3':
    frequency_range:
    - 1
    - 4
    time_range:
    - -20
    - 20
