subject_code: subHUP064
project_name: fingerprinting
epoch_file_name: subHUP064_seizure
load_electrodes: 3-87
reference_name: bipolar
time_window:
- -20
- 20
time_bandwidth: 3
xyflip: no
verbose: no
plot_on: no
num_workers: 31.0
parallel: yes
detrend_opt: linear
weighting: unity
min_nfft: 0
num_tapers: ~
frequency_range:
- 1
- 200
window_params:
- 2.0
- 0.5
baseline_method: decibel
baseline:
- - -1
  - -0.2
type: power
intervals:
- - -1.0
  - 2.0
reference: default
save_pipeline: yes
freq_list:
  f1:
  - 1
  - 7
  f3:
  - 8
  - 12
  f4:
  - 13
  - 31
  f5:
  - 32
  - 150
condition: sz2 (6)
