subject_code: subHUP064
project_name: fingerprinting
epoch_file_name: subHUP064_seizure
load_electrodes: 3-87
reference_name: noref
time_window:
- -60
- 60
epoch: sz2
num_windows: 100
SOZ_string: 12-13,17-21,25-29,31,33-37,39,42-43,51-52
time_bandwidth: 3
xyflip: no
verbose: no
plot_on: no
num_workers: 7
parallel: yes
detrend_opt: linear
weighting: unity
min_nfft: 0
num_tapers: ~
frequency_range:
- 1
- 200
sampling_frequency: 1024
window_params:
- 2.0
- 0.5
baseline_method: decibel
baseline:
- - -1
  - -0.2
type: power
intervals:
- - -1.0
  - 2.0
reference: default
save_pipeline: yes
