analysis_time_frequencies:
  '1':
    frequency_range:
    - 1
    - 200
    time_range:
    - -1
    - 2
  '2':
    frequency_range:
    - 55.8
    - 200
    time_range:
    - -0.4
    - 1.4
condition: sz (1)
reference: default
window_params:
- 2.0
- 0.5
frequency_range:
- 1
- 200
num_tapers: ~
min_nfft: 0
weighting: unity
detrend_opt: linear
parallel: yes
num_workers: 7.0
plot_on: no
verbose: no
xyflip: no
time_bandwidth: 3
time_window:
- -1
- 2
reference_name: noref
load_electrodes: 3-10
epoch_file_name: subHUP064_seizure
project_name: fingerprinting
subject_code: subHUP064
soz_electrodes: 3
heatmap_name_type: number
