time_windows:
- 0
- 20
electrodes: 1-4,7-36,42-43,46-69,72-95
epoch_name: sz1 (2)
subject_code: subummc005
ordered: yes
heatmap_name_type: number
resect_electrodes: ''
soz_electrodes: ''
project_name: Retrostudy
epoch_file_name: subummc005_seizure
selected_electrode: 1
load_electrodes: 6-7,34,36,42,44
reference_name: car
time_window:
- -10
- 20
time_bandwidth: 3
xyflip: no
verbose: no
plot_on: no
num_workers: 31.0
parallel: yes
detrend_opt: linear
weighting: unity
min_nfft: 0
num_tapers: ~
frequency_range:
- 0.5
- 150.0
window_params:
- 2.5
- 0.5
reference: common_average
condition: sz1 (2)
analysis_time_frequencies:
  '1':
    frequency_range:
    - 90
    - 150
    frequency_preset_delta: 0
    frequency_preset_theta: 0
    frequency_preset_alpha: 0
    frequency_preset_beta: 0
    frequency_preset_gamma: 0
    frequency_preset_high_gamma: 0
    time_range:
    - -10
    - 20
plot_resect_elec: no
resect_elec: '0'
SOZ_elec: '0'
text_size: 5.0
organize_top: no
label: numeric
plot_SOZ_elec: no
analysis_windows:
  '1':
    frequency_range:
    - 13.0
    - 31.0
    time_range:
    - 0.0
    - 20.0
time_stat_start: 0.0
time_stat_end: 10.0
end_time_baseline: 0
start_time_baseline: 0.0
baselined: no
scale: None
baseline: 30s before sz1 (1)
decibal: no
ML_time_range:
- 0
- 20
show_ML: no
epoch_choice__trial_ends: 20
epoch_choice__trial_starts: -10
save_path: /Volumes/bigbrain/scripts/sean/stats/updated_plots/
