SOZ_elec: '0'
resect_elec: '0'
plot_resect_elec: no
analysis_time_frequencies:
  '1':
    frequency_range:
    - 0.5
    - 4.0
    time_range:
    - 0.0
    - 10.0
condition: sz2 (4)
reference: common_average
window_params:
- 2.5
- 0.5
frequency_range:
- 0.0
- 250.0
num_tapers: ~
min_nfft: 0
weighting: unity
detrend_opt: linear
parallel: yes
num_workers: 31.0
plot_on: no
verbose: no
xyflip: no
time_bandwidth: 3.0
time_window:
- 0.0
- 10.0
reference_name: car
load_electrodes: 2-23, 25-30, 32-34, 36-53
epoch_file_name: subumf002_seizure
project_name: Retrostudy
soz_electrodes: ''
resect_electrodes: ''
heatmap_name_type: number
ordered: yes
subject_code: subumf002
epoch_name: subHUP064_seizure
electrodes: 3,4-87
time_windows:
- -10.0
- 10.0
time_stat_end: 10.0
time_stat_start: 0.0
analysis_windows:
  '1':
    frequency_range:
    - 13.0
    - 31.0
    time_range:
    - 0.0
    - 10.0
plot_SOZ_elec: no
label: numeric
organize_top: no
text_size: 5.0
baseline: 30s before sz2 (3)
scale: None
baselined: yes
start_time_baseline: 0.0
end_time_baseline: 10
