condition: sz1 (4)
freq_list:
  f1:
  - 13
  - 31
save_pipeline: yes
reference: default
intervals:
- - -1.0
  - 2.0
type: power
baseline:
- - -1
  - -0.2
baseline_method: decibel
window_params:
- 2.0
- 0.5
frequency_range:
- 1
- 200
num_tapers: ~
min_nfft: 0
weighting: unity
detrend_opt: linear
parallel: yes
num_workers: 31.0
plot_on: no
verbose: no
xyflip: no
time_bandwidth: 3
time_window:
- -20
- 20
reference_name: bipolar
load_electrodes: 3-87
SOZ_elec: 12,13,17-21,25-29,31,42,43,51,52,
plot_SOZ_elec: yes
epoch_file_name: subHUP064_seizure
project_name: fingerprinting
subject_code: subHUP064
label: names
