SOZ_elec: '0'
resect_elec: '0'
plot_resect_elec: no
analysis_time_frequencies:
  '1':
    frequency_range:
    - 13
    - 30
    time_range:
    - -1
    - 2
condition: sz1 (4)
reference: common_average
window_params:
- 2.5
- 0.5
frequency_range:
- 0
- 256
num_tapers: ~
min_nfft: 0
weighting: unity
detrend_opt: linear
parallel: yes
num_workers: 31.0
plot_on: no
verbose: no
xyflip: no
time_bandwidth: 3
time_window:
- -20
- 20
reference_name: common_average
load_electrodes: 3-88
epoch_file_name: subHUP064_seizure
project_name: Retrostudy
soz_electrodes: ''
resect_electrodes: ''
heatmap_name_type: number
ordered: yes
subject_code: subHUP064
epoch_name: subHUP064_seizure
electrodes: 3,4-87
time_windows:
- -30.0
- 30.0
time_stat_end: 10.0
time_stat_start: 0.0
analysis_windows:
  '1':
    frequency_range:
    - 13.0
    - 31.0
    time_range:
    - 0.0
    - 30.0
plot_SOZ_elec: no
label: numeric
organize_top: no
text_size: 5.0
baseline: 60s before sz1 (2)
scale: None
baselined: yes
