heatmap_name_type: number
soz_electrodes: 3
subject_code: DemoSubject
project_name: demo
epoch_file_name: auditory_onset
load_electrodes: 13-16,24
reference_name: noref
time_window:
- -1
- 2
time_bandwidth: 3
xyflip: no
verbose: no
plot_on: no
num_workers: 31.0
parallel: yes
detrend_opt: linear
weighting: unity
min_nfft: 0
num_tapers: ~
frequency_range:
- 1
- 200
window_params:
- 0.2
- 0.01
reference: default
condition: sz (1)
analysis_time_frequencies:
  '1':
    frequency_range:
    - 3
    - 200
    text_min_frequency_range: 1
    text_max_frequency_range: 200
    time_range:
    - -1
    - 2
