time_stat_end: 10.0
time_windows:
- -30.0
- 30.0
electrodes: 3,4-87
epoch_name: subHUP064_seizure
subject_code: subHUP074
ordered: yes
heatmap_name_type: number
resect_electrodes: ''
soz_electrodes: ''
project_name: Retrostudy
epoch_file_name: subHUP074_seizure
load_electrodes: 1-14,17-22,25-55,57-89,91-95,97-100,102-122
reference_name: common_average
time_window:
- -20
- 20
time_bandwidth: 3
xyflip: no
verbose: no
plot_on: no
num_workers: 31.0
parallel: yes
detrend_opt: linear
weighting: unity
min_nfft: 0
num_tapers: ~
frequency_range:
- 0
- 250
window_params:
- 2.5
- 0.5
reference: common_average
condition: sz1 (3)
analysis_time_frequencies:
  '1':
    frequency_range:
    - 13
    - 30
    time_range:
    - -20
    - 20
plot_resect_elec: no
resect_elec: '0'
SOZ_elec: '0'
baseline: 60s before sz1 (1)
text_size: 5.0
organize_top: no
label: numeric
plot_SOZ_elec: no
analysis_windows:
  '1':
    frequency_range:
    - 13.0
    - 31.0
    time_range:
    - 0.0
    - 30.0
time_stat_start: 0.0
end_time_baseline: 30
start_time_baseline: 0
baselined: yes
scale: None
