SOZ_elec: '0'
resect_elec: '0'
plot_resect_elec: no
analysis_time_frequencies:
  '1':
    frequency_range:
    - 90.0
    - 256.0
    time_range:
    - 0.0
    - 30.0
condition: sz1 (2)
reference: common_average
window_params:
- 2.5
- 0.5
frequency_range:
- 0.0
- 250.0
num_tapers: ~
min_nfft: 0
weighting: unity
detrend_opt: linear
parallel: yes
num_workers: 31.0
plot_on: no
verbose: no
xyflip: no
time_bandwidth: 3.0
time_window:
- 0.0
- 30.0
reference_name: car
load_electrodes: 1-4,7-36,42-43,46-69,72-95
selected_electrode: 1
epoch_file_name: subpt01_seizure
project_name: Retrostudy
soz_electrodes: 33-34,62-69
resect_electrodes: 33-34,62-69
heatmap_name_type: number
ordered: no
subject_code: subpt01
epoch_name: sz1 (2)
electrodes: 1-4,7-36,42-43,46-69,72-95
time_windows:
- 0
- 30.0
time_stat_end: 30.0
time_stat_start: 0.0
analysis_windows:
  '1':
    frequency_range:
    - 13.0
    - 31.0
    time_range:
    - 0.0
    - 30.0
plot_SOZ_elec: no
label: numeric
organize_top: no
text_size: 5.0
decibal: no
baseline: 30s before sz1 (1)
scale: None
baselined: yes
start_time_baseline: 0.0
end_time_baseline: 10
threshold: 0.9
