---
title: "RAVE Preprocess: Notch Filter"
output:
  html_document: default
  pdf_document: default
editor_options: 
  chunk_output_type: console
---

```{r setup, include = FALSE}
# This code block sets up the engine environment
# Please do not remove me
raveio::pipeline_setup_rmd("notch_filter")
```

```{rave load_subject, language = "R", export = "subject", cue = "always", format = "rave-subject"}
subject <- raveio::RAVESubject$new(
  project_name = project_name, 
  subject_code = subject_code, 
  strict = FALSE
)
```


```{rave check_imported_electrodes, language = "R", export = "imported_electrodes", cue = "always"}
imported_electrodes <- subject$electrodes[
  subject$preprocess_settings$data_imported
]

if(!length(imported_electrodes)){
  stop("The subject exists but its signal has not been imported yet.")
}

```

```{rave check_filter_settings, language = "R", export = "filter_settings", cue = "always"}

lb <- unlist(notch_filter_lowerbound)
ub <- unlist(notch_filter_upperbound)
if(length(lb) != length(ub)) {
  stop(sprintf("Notch filter lower bound length should match with the upper bound length (%d vs %d)", length(lb), length(ub)))
}

if(length(lb)) {
  
  if(!all(lb < ub)) {
    sel <- lb >= ub
    lb <- lb[sel]
    ub <- ub[sel]
    stop("Notch filter lower bounds must be uniformly smaller than the upper bounds: (", paste0(lb, ">", ub, collapse = ", "), ")")
  }
  
}

filter_settings <- list(
  lb = lb,
  ub = ub,
  domain = 1
)

```


```{rave apply_Notch_filters, language = "R", export = "apply_notch", cue = "always"}

blocks <- subject$preprocess_settings$blocks
electrodes <- imported_electrodes
filters <- filter_settings

fmt <- file.path(subject$preprocess_path, "voltage", "electrode_%d.h5")
sample_rates <- subject$raw_sample_rates
sample_rates <- sapply(electrodes, function(e){
  sample_rates[subject$electrodes == e]
})

dipsaus::lapply_async2(
  seq_along(electrodes), function(ii){
    e <- electrodes[[ii]]
    srate <- sample_rates[[ii]]
    h5_path <- sprintf(fmt, e)
    h5_names <- gsub("^/", "", raveio::h5_names(h5_path))
    sel <- sprintf("raw/%s", blocks) %in% h5_names
    if(!all(sel)) {
      stop(sprintf(
        "Cannot find imported block(s): %s (electrode %s)",
        blocks[!sel], e
      ))
    }
    for(block in blocks){
      # cat(block, e, "\n")
      signal <- raveio::load_h5(h5_path, sprintf("raw/%s", block), ram = TRUE)
      
      # Apply notch filter if filters exist, otherwise do NOT do anything
      if(length(filters$lb)) {
        signal <- ravetools::notch_filter(s = signal, sample_rate = srate, lb = filters$lb, ub = filters$ub, domain = filters$domain)
      }
      raveio::save_h5(x = signal, file = h5_path, name = sprintf("notch/%s", block), chunk = 1024, replace = TRUE, ctype = "numeric")
    }
  }, plan = FALSE, callback = function(ii){
    sprintf("Applying Notch filters|Electrode - %s", electrodes[[ii]])
  }
)

# save to subject
preproc <- raveio::RAVEPreprocessSettings$new(subject = subject$subject_id)

for(e in electrodes){
  preproc$data[[as.character(e)]]$notch_filtered <- TRUE
}
preproc$save()

apply_notch <- list(
  electrodes = electrodes,
  notch_filter_lowerbound = filters$lb,
  notch_filter_upperbound = filters$ub,
  timestamp = strftime(Sys.time(), usetz = TRUE)
)

subject$set_default(
  namespace = "notch_filter",
  key = "parameters",
  value = apply_notch
)


```


```{rave generate_diagnostic_plots, language = "R", export = "diagnostic_plots", cue = "always"}
diagnostic_plots <- FALSE
params <- as.list(diagnostic_plot_params)

if(!isTRUE(params$dry_run)) {
  background <- params$background
  foreground <- params$foreground
  
  if(!length(background) == 1) {
    background <- "white"
  }
  if(!length(foreground) == 1) {
    foreground <- "black"
  }
  
  
  if(length(params$path) == 1) {
    grDevices::pdf(file = params$path, width = 12, height = 7, onefile = TRUE, bg = background, fg =  foreground,useDingbats = FALSE)
     
    on.exit({
      grDevices::dev.off()
    }, add = TRUE)
    
  }
  
  winlen <- as.numeric(params$window_length)
  if(!length(winlen) || is.na(winlen)) {
    winlen <- "auto"
  }
    
  max_freq <- as.numeric(params$max_frequency)
  if(!length(max_freq) || is.na(max_freq)) {
    max_freq <- 300
  }
  nbins <- as.numeric(params$histogram_bins)
  if(!length(nbins) || is.na(nbins)) {
    nbins <- 50
  }
  
  
  font_size <- as.numeric(params$font_size)
  if(!length(font_size) || is.na(font_size)) {
    font_size <- 2
  }
  quiet <- isTRUE(params$quiet)
  
  
  diagnostic_plots <- diagnose_notch_filters(
    subject = subject,
    electrodes = imported_electrodes,
    max_freq = max_freq,
    winlen = winlen,
    nbins = nbins,
    bg = background,
    fg = foreground,
    cex = font_size,
    std = 3,
    lwd = 0.3,
    quiet = quiet
  )
}
```

## Build, Visualize, & Run

Please make sure the following code block is at the end of your pipeline file. This block will build the pipeline and generate a `make-notch_filter.R` script with your pipeline markdown file. `RAVE` will use the generated pipeline script to execute the pipeline in the dashboard application, or in massive production mode.

```{r build, echo=FALSE, results='hide'}
Sys.setenv("RAVE_PIPELINE" = normalizePath("."))
build_pipeline(make_file = "make-notch_filter.R")
raveio::pipeline_visualize()
```


