project_name: "devel"
subject_code: "PAV007"
reference_choice: noref
epoch_choice: "stimulation"
epoch_choice__trial_ends: 2.0
epoch_choice__trial_starts: -1.0
electrodes: 14-16
analysis_electrodes: 14-15
reference_name: noref
baseline_settings:
  method: "subtract_mean"
  source: ~
  global: no
  window:
  - -1
  - -0.5
interpolate:
  epoch_column: Duration
  method: "linear"
analysis_event: "onset"
downsample: 30
