analysis_electrodes: '14'
analysis_event: Onset
baseline_settings:
  method: subtract_mean
  source: ~
  global: no
  window:
  - -1.0
  - -0.79
condition_groups:
  '1':
    group_name: A
    group_conditions:
    - last_a
  '2':
    group_name: V
    group_conditions:
    - last_v
  '3':
    group_name: AV
    group_conditions:
    - last_av
  '4':
    group_name: inc2
    group_conditions:
    - AdriveVlast
  '5':
    group_name: inc1
    group_conditions:
    - AlastVknown
downsample: 2
epoch_choice: auditory_onset
epoch_choice__trial_ends: 2
epoch_choice__trial_starts: -1
interpolate:
  method: none
  from: Onset
  to: Onset
loaded_electrodes: 13-16,24
project_name: demo
reference_name: default
subject_code: DemoSubject
