subject_code: PAV006
fsl_path: /usr/local/fsl
freesurfer_path: /Applications/freesurfer/7.4.1
project_name: devel
path_mri: junk/MRI_reference.nii
skip_recon: no
afni_path: /Users/dipterix/abin
params:
  nii_t1: MRI_RAW.nii
  nii_ct: POST_IMPLANT_CT_1_STEALTH_20220824232445_2.nii
  template_brain: ~
  dcm2niix:
    merge: Auto
    float: 'Yes'
    crop: 'No'
  segmentation:
    program: recon-all
    flag: -all
    fresh_start: no
  niftyreg:
    reference: MRI_RAW.nii
    reg_type: rigid
    interp: trilinear
  ants:
    reference: MRI_RAW.nii
    reg_type: Rigid
    aff_metric: mattes
    syn_metric: mattes
  flirt:
    reference: MRI_RAW.nii
    dof: 6
    cost: mutualinfo
    search: 90
    searchcost: mutualinfo
  nipy:
    reference: MRI_RAW.nii
    clean_source: yes
    inverse_target: yes
    precenter_source: yes
    reg_type: rigid
    similarity: crl1
    interp: pv
    optimizer: powell
  afni:
    reference: MRI_RAW.nii
dcm2niix_path: /opt/homebrew/Cellar/dcm2niix/1.0.20230411/bin/dcm2niix
path_ct: junk/CT_RAW.nii.gz
skip_coregistration: no
