---
title: "RAVE Power Explorer"
format: html
output:
  html_document: default
  pdf_document: default
editor_options:
  chunk_output_type: console
chunk_output_type: console
---

```{r setup, include = FALSE}
# This code block sets up the engine environment
# Please do not remove me
raveio::pipeline_setup_rmd("power_explorer")

options(knit_rave_pipelines = TRUE)

```

```{rave check_load_power, language = "R", export = "repository", format = "rave_prepare_power", cue = "always"}
subject <- raveio::as_rave_subject(subject_id = sprintf("%s/%s", project_name, subject_code))

repository <- raveio::prepare_subject_power(
  subject = subject, electrodes = loaded_electrodes, 
  epoch_name = epoch_choice, reference_name = reference_name,
  time_windows = c(epoch_choice__trial_starts, epoch_choice__trial_ends))

repository
```

```{rave check_requested_electrodes, language = "R", export = "requested_electrodes"}
requested_electrodes <- dipsaus::parse_svec(analysis_electrodes, sep=',|;', connect  = ':-')
requested_electrodes <- requested_electrodes[requested_electrodes %in% repository$power$dimnames$Electrode]
if(!length(requested_electrodes)){ stop("No electrode selected") }
```

```{rave check_analysis_settings, language = "R", export = "analysis_settings_clean"}

check_range <- function(x, lim, lbl) {
  if(!all(x %within% lim)) stop(sprintf('Requested %s [%s] not within available range [%s]', lbl, str_collapse(range(x), ':'), str_collapse(range(lim), ':')), call. = FALSE)
}

# check repo settings
if(length(repository$time_windows) != 1) stop('discontinuous time windows not supported')

# first ensure all analysis settings are vectors, not lists
analysis_settings_clean <- lapply(analysis_settings, function(as) {
  as$time %<>% unlist
  as$frequency %<>% unlist
  
  if(is.null(as$label) || nchar(as$label) < 1) {
    as$label <- paste('Window', rand_string(length = 4))
  }
  
  if(is.null(as$censor_info)) {
    as$censor_info <- list(
      enabled=FALSE, window = 0:1
    )
  }
  
  return(as)
})

# ensure baseline choices are valid
ua <- get_unit_of_analysis(names=TRUE)
if(!baseline_settings$unit_of_analysis %in% ua) {
  stop(sprintf('Requested unit of analysis "%s" must be one of: %s', baseline_settings$unit_of_analysis, str_collapse(ua)))
}

ua <- get_baseline_scope(names=TRUE)
if(!baseline_settings$scope %in% ua) {
  stop(sprintf('Requested baseline scope "%s" must be one of: %s', baseline_settings$scope, str_collapse(ua)))
}

# ensure analysis choices are valid
lapply(analysis_settings_clean, function(setting) {
  check_range(setting$frequency, unlist(repository$frequency), 'frequency')
  check_range(setting$time, unlist(repository$time_windows), 'analysis time')
})

names(analysis_settings_clean) <- sapply(analysis_settings_clean, `[[`, 'label')

#ensure no duplicated names
dd <- duplicated(sapply(analysis_settings_clean, `[[`, 'label'))
while(sum(dd)) {
  for(w in which(dd)) {
    analysis_settings_clean[[w]]$label = paste(analysis_settings_clean[[w]]$label,
                                               rand_string(length = 4))
  }
  dd <- duplicated(sapply(analysis_settings_clean, `[[`, 'label'))
}

# copy in the censor variable into the analysis settings. if the censoring changes,
# basically everything changes
for(ii in seq_along(analysis_settings_clean)) {
  analysis_settings_clean[[ii]]$censor_info = time_censor
  analysis_settings_clean[[ii]]$censor_info$window %<>% unlist
}


#### checks on condition groupings
for(ii in seq_along(first_condition_groupings)) {
  if(!nzchar(first_condition_groupings[[ii]]$label)) {
    first_condition_groupings[[ii]]$label = paste('Group', ii)
  }
}

#ensure no duplicate condition names
dd <- duplicated(sapply(first_condition_groupings, `[[`, 'label'))
while(sum(dd)) {
  for(w in which(dd)) {
    first_condition_groupings[[w]]$label = paste(first_condition_groupings[[w]]$label,
                                                 rand_string(length = 4))
  }
  dd <- duplicated(sapply(first_condition_groupings, `[[`, 'label'))
}

# ensure second-level trial groupings accord with the first level
fcg <- c(unlist(sapply(first_condition_groupings, `[[`, 'conditions')))
if(isTRUE(enable_second_condition_groupings)) {
  scg <- c(unlist(sapply(second_condition_groupings, `[[`, 'conditions')))
  stopifnot(setequal(scg,fcg))
  stopifnot(all(!duplicated(scg)))
}

# we can't have duplicates in trial groupings
if(any(duplicated(fcg))) {
  warning("Duplication in first factor, results may be unreliable")
}

if(is.list(trial_outliers_list)) {
  trial_outliers_list %<>% unlist
}


## add in the subejct code to the analysis settings
for(ii in seq_along(analysis_settings_clean)) {
  analysis_settings_clean[[ii]]$subject_code = subject_code
}

analysis_checks_passed=TRUE
```

```{rave calculate_baseline, language = "R", export = "baselined_power", cue = "always", format = "user-defined-r"}
raveio::power_baseline(
  x = repository,
  baseline_windows = baseline_settings$window,
  method = get_unit_of_analysis(baseline_settings$unit_of_analysis),
  units = get_baseline_scope(baseline_settings$scope),
  signal_type = "LFP",
  electrodes = requested_electrodes
)
baselined_power <- repository$power$baselined
```

```{rave build_trial_details, language = "R", export = "trial_details"}
# remove empty FCGs
k = sapply(lapply(first_condition_groupings, `[[`, 'conditions'), length)
fcgs <- first_condition_groupings[k>0]

all_trials <- c(unname(unlist(lapply(fcgs, `[[`, 'conditions'))))

tbl <- subset(repository$epoch$table, Condition %in% all_trials,
              select=c('Trial', 'Condition'))

f1 <- rutabaga::rbind_list(
  lapply(fcgs, function(ff) {
    # ff = fcgs[[1]]
    data.frame('Factor1'=ff$label, 'Condition'=ff$conditions)
  })
)

trial_details <- merge(tbl, f1, by=c('Condition'))

if(isTRUE(enable_second_condition_groupings)) {
  f2 <- rutabaga::rbind_list(
    lapply(second_condition_groupings, function(ff) {
      # ff = second_condition_groupings[[1]]
      data.frame('Factor2'=ff$label, 'Condition'=ff$conditions)
    })
  )
  
  trial_details %<>% merge(f2, by=c('Condition'))
}
trial_details = trial_details[order(trial_details$Trial),]

# put the factors in order
trial_details$Factor1 %<>% factor(levels = sapply(fcgs, `[[`, 'label'))

if(!is.null(trial_details$Factor2)) {
  trial_details$Factor2 %<>% factor(levels = sapply(second_condition_groupings, `[[`, 'label'))
}

# add rownames to trial details to make for easy selection by trial
rownames(trial_details) = trial_details$Trial

```

```{rave build_analysis_groups, language = "R", export = "analysis_groups"}
# build the groups from the first_condition_groupings variable (eventually add in the 2 cond group)
if(isTRUE(enable_second_condition_groupings)) {
  # remove empty FCGs
  
  by_group <- split(trial_details,
                    list(trial_details$Factor1, trial_details$Factor2)
  )
  
  names(by_group) <- paste(rep(levels(trial_details$Factor1),each=nlevels(trial_details$Factor2)), levels(trial_details$Factor2), sep='.')
  
  analysis_groups <- vector('list', length(by_group))
  for(ii in seq_along(by_group)) {
    analysis_groups[[ii]] <- list(
      label = names(by_group)[[ii]],
      conditions = unique(by_group[[ii]]$Condition),
      condition_per_trial = by_group[[ii]]$Condition,
      trials = by_group[[ii]]$Trial,
      index = ii,
      has_trials = TRUE#,
      # this shouldn't be requested electrodes, this should be set based on some grouping variable like ROI
      #electrodes = requested_electrodes
    )
  }
  
  attr(analysis_groups, 'meta') <- trial_details
  
} else {
  analysis_groups <- mapply(function(cg, ii) {
    trials <- c()
    if(length(cg$conditions)>0) {
      trials <- repository$epoch$table$Trial[
        repository$epoch$table$Condition %in% cg$conditions
      ]
    }
    
    list(
      label = cg$label,
      conditions = cg$conditions,
      trials = trials,
      index = ii,
      has_trials = length(trials) > 0#,
      # electrodes = requested_electrodes
    )
  }, first_condition_groupings, seq_along(first_condition_groupings), SIMPLIFY = FALSE)
  
  # remove groups that have no data
  has_trials <- which(sapply(analysis_groups, `[[`, 'has_trials'))
  analysis_groups = analysis_groups[has_trials]
}

if(length(analysis_groups) < 1) stop('No trials available in condition groups')

# bring up the label as the element name for ease of use
names(analysis_groups) <- sapply(analysis_groups, `[[`, 'label')

```

```{rave build_pluriform_power, language = "R", export = "pluriform_power", format = "user-defined-r"}
# Depends on baselined_power, 
epoch_event_types = get_available_events(repository$epoch$columns)

baselined_power_data <- subset(baselined_power,
                               Electrode ~ Electrode %in% requested_electrodes)

pluriform_power <- sapply(analysis_groups, function(ag) {
  # ag <- analysis_groups[[1]]
  sapply(analysis_settings_clean, function(as) {
    # as <- analysis_settings_clean[[1]]
    p <- get_pluriform_power(
      baselined_data=baselined_power_data,
      trial_indices = ag$trials,
      events = repository$epoch$table,
      epoch_event_types = epoch_event_types,
      trial_outliers_list=unlist(trial_outliers_list),
      event_of_interest = as$event,
      sample_rate = repository$subject$power_sample_rate
    )
    list('data'=p, 'settings'=as, 'outliers' = trial_outliers_list)
  }, simplify = FALSE, USE.NAMES = TRUE)
}, simplify = FALSE, USE.NAMES = TRUE)

# now create frequency-subsetted versions of the data
for(gg in seq_along(pluriform_power)) {
  for(aa in seq_along(pluriform_power[[gg]])) {
    fi <- as.numeric(dimnames(pluriform_power[[gg]][[aa]]$data$shifted_data)$Frequency) %within% 
      unlist(pluriform_power[[gg]][[aa]]$settings$frequency)
    
    pluriform_power[[gg]][[aa]]$data$shifted_data_Fsub <- pluriform_power[[gg]][[aa]]$data$shifted_data[fi,,,,drop=FALSE]
    
    pluriform_power[[gg]][[aa]]$data$shifted_clean_data_Fsub <-  pluriform_power[[gg]][[aa]]$data$shifted_clean_data[fi,,,,drop=FALSE]
  }
}
```

```{rave build_overall_tf_data, language="R", export ="by_frequency_over_time_data"}
build_data <- function(data, analysis_settings, condition_group, baseline_settings, ...) {
  dn <- dimnames(data)
  stopifnot(c('Time', 'Frequency') == names(dn)[2:1])
  
  res <- list(
    data = raveio::collapse2(data, keep = 2:1, method = "mean"),
    
    x = as.numeric(dn$Time),
    y = as.numeric(dn$Frequency),
    
    xlab='Time (s)', ylab='Frequency',
    zlab='Mean ' %&% baseline_settings$unit_of_analysis
  )
  
  # determine range under censoring
  if(isTRUE(analysis_settings$censor_info$enabled)) {
    ti = res$x %within% settings$censor_info$window
    res$range <- range(res$data[!ti,])
  } else {
    res$range <- range(res$data)
  }
  
  return(res)
}

by_frequency_over_time_data <- data_builder(pluriform_power = pluriform_power,
                                            condition_group = analysis_groups, 
                                            baseline_settings = baseline_settings,
                                            build_data, data_type = 'shifted_clean_data')
```

```{rave build_tf_correlation_data, language="R", export = "by_frequency_correlation_data"}

# for each analysis settings in the by_frequency_over_time_data, get the correlation within the time window

# get the average response for _each_ frequency on _each_ trial,
# averaged across electrodes and time points within the analysis window

build_data <- function(data, analysis_settings, condition_group, baseline_settings, ...) {
  dn <- dimnames(data)
  tm <- as.numeric(dn$Time)
  
  ti <- tm %within% analysis_settings$time
  if(isTRUE(analysis_settings$censor_info$enabled)) {
    ti = ti & !(tm %within% analysis_settings$censor_info$window)
  }
  rawdata <- ravetools::collapse(data[,ti,,,drop=FALSE], keep = c(3,1))
  
  res <- list(
    data = cor(rawdata),
    xlab='Frequency',
    ylab='Frequency',
    zlab='Pearson correlation across trials',
    x = as.numeric(dn$Frequency),
    y = as.numeric(dn$Frequency),
    rawdata <- rawdata
  )
  res$range = range(res$data)
  
  return(res)  
}

by_frequency_correlation_data <- data_builder(
  pluriform_power = pluriform_power,
  condition_group = analysis_groups, 
  baseline_settings = baseline_settings,
  build_data, data_type = 'shifted_clean_data'
)
```

```{rave plot_bfcd, language='R', export='plot_bfcd_success'}
plot_bfcd_success = FALSE
plot_by_frequency_correlation(by_frequency_correlation_data)

plot_bfcd_success = TRUE

```

```{rave build_by_trial_tf_data, language="R", export ="by_trial_tf_data"}
build_data <- function(dd, settings) {
  to_keep <- sapply(c('Time', 'Trial'), which.equal, names(dimnames(dd)))
  res <- list(
    data = ravetools::collapse(dd, keep = to_keep),
    xlab='Time (s)', ylab='Original Trial #',
    zlab='Mean ' %&% baseline_settings$unit_of_analysis
  )
  
  res[c('x', 'y')] <- dimnames(dd)[to_keep] %>% lapply(as.numeric)
  
  res$N = dim(dd)[4L]
  
  if(isTRUE(settings$censor_info$enabled)) {
    ti = res$x %within% settings$censor_info$window
    res$range <- range(res$data[!ti,])
  } else {
    res$range <- range(res$data)
  }
  
  return(res)
}

by_trial_tf_data <- lapply(pluriform_power, function(pp) {
  # rm(pp) <- pluriform_power[[1]]
  if(all(
    1 == length(table(sapply(pp, function(pi) pi$settings$event))),
    1 == length(table(sapply(pp, function(pi) str_collapse(pi$settings$frequency))))
  )) {
    # all analysis groups have the same time=0 and the same frequency range,
    # so we can show them on the same plot      
    build_data(pp[[1]]$data$shifted_data_Fsub, pp[[1]]$settings)
  } else {
    # analysis groups have different time shifts/frequencies, so they can not be shown on the same plot
    sapply(pp, function(ppa) {
      build_data(ppa$data$shifted_data_Fsub, ppa$settings)
    }, simplify = FALSE, USE.NAMES = TRUE)
  }
})

```

```{rave build_over_time_by_electrode_data, language="R", export ="over_time_by_electrode_data"}

build_data <- function(data, analysis_settings, condition_group, baseline_settings, ...) {
  dm <- dimnames(data)
  to_keep <- sapply(c('Time', 'Electrode'), which.equal, names(dm))
  res <- list(
    data = ravetools::collapse(data, keep = to_keep),
    xlab='Time (s)',
    ylab='Electrode #',
    zlab='Mean ' %&% baseline_settings$unit_of_analysis,
    condition_group = condition_group$label,
    electrodes = as.integer(dm$Electrode),
    subject_code = subject_code
  )
  
  res[c('x', 'y')] <- dimnames(data)[to_keep] %>% lapply(as.numeric)
  
  res$N = length(dm$Trial)
  
  if(isTRUE(analysis_settings$censor_info$enabled)) {
    ti = res$x %within% analysis_settings$censor_info$window
    res$range <- range(res$data[!ti,])
  } else {
    res$range <- range(res$data)
  }
  
  return(res)
}

over_time_by_electrode_data <- data_builder(pluriform_power = pluriform_power,
                                            condition_group = analysis_groups, 
                                            baseline_settings = baseline_settings,
                                            build_data)


```

```{rave plot_over_time_by_electrode_data_data, language='R', export='betfd_success', cue="always"}

betfd_success <- tryCatch({
  draw_many_heat_maps(over_time_by_electrode_data)
  
  TRUE
}, error=function(e) {
  e
})
```

```{rave build_over_time_by_condition_data, language="R", export ="over_time_by_condition_data"}
build_data <- function(dd, settings) {
  to_keep <- sapply(c('Time', 'Electrode'), which.equal, names(dimnames(dd)))
  res <- list(
    data = ravetools::collapse(dd, keep = to_keep),
    xlab='Time (s)',
    ylab='Mean ' %&% baseline_settings$unit_of_analysis,
    zlab=NA
  )
  
  # no get m_se across electrode at each time point
  res$data <- cbind(
    .rowMeans(res$data, nrow(res$data), ncol(res$data)),
    sqrt(diag(dipsaus::fastcov2(t(res$data))) / ncol(res$data))
  )
  
  ind <- is.nan(res$data[,2]) | !is.finite(res$data[,2])
  if(length(ind) > 0) {
    res$data[ind,2] = 0
  }
  
  res$x <- as.numeric(dimnames(dd)$Time)
  res$y <- NA
  res$N = length(dimnames(dd)$Electrode)
  
  if(isTRUE(settings$censor_info$enabled)) {
    ti = res$x %within% settings$censor_info$window
    res$range <- range(rutabaga::plus_minus(res$data[!ti,]))
  } else {
    res$range <- range(rutabaga::plus_minus(res$data))
  }
  
  res$settings = settings
  
  return(res)
}

over_time_by_condition_data <- lapply(pluriform_power, function(pp) {
  sapply(pp, function(ppa) {
    build_data(ppa$data$shifted_clean_data_Fsub, ppa$settings)
  }, simplify = FALSE, USE.NAMES = TRUE)
})

# bring down the meta data to the plotting level for ease of use
for(ii in seq_along(over_time_by_condition_data)) {
  for(jj in seq_along(over_time_by_condition_data[[ii]])) {
    over_time_by_condition_data[[ii]][[jj]]$data_label = 
      names(over_time_by_condition_data)[[ii]]
    
    over_time_by_condition_data[[ii]][[jj]]$time_window_label =
      names(over_time_by_condition_data[[ii]])[[jj]]
  }
}
```

```{rave plot_over_time_data, language='R', export='plot_over_time_by_condition_result', cue='always'}
plot_over_time_by_condition_result = TRUE
# plot_over_time_by_condition(over_time_by_condition_data, F, F)
```

```{rave build_scatter_bar_data, language="R", export ="scatter_bar_data"}
build_data <- function(dd, settings) {
  dm <- dimnames(dd)
  to_keep <- which.equal('Trial', names(dm))
  
  # make sure the time dimension is index 2
  stopifnot(which.equal('Time', names(dm)) == 2)
  
  t_ind <- as.numeric(dm$Time) %within% unlist(settings$time)
  
  if(isTRUE(settings$censor_info$enabled)) {
    t_ind = t_ind & !(
      as.numeric(dm$Time) %within% unlist(settings$censor_info$window)
    )
  }
  
  res <- list(
    data = ravetools::collapse(dd[,t_ind,,,drop=FALSE], keep = to_keep),
    xlab='Group',
    ylab='Mean ' %&% baseline_settings$unit_of_analysis,
    zlab=NA
  )
  res$range <- range(res$data)
  
  # here maybe store the jitter?
  #FIXME
  res$x <- NA
  res$y <- NA
  res$N = length(dimnames(dd)$Trial)
  
  return(res)
}

# scatter_bar_data <- lapply(pluriform_power, function(pp) {
#   sapply(pp, function(ppa) {
#     build_data(ppa$data$shifted_clean_data_Fsub, ppa$settings)
#   }, simplify = FALSE, USE.NAMES = TRUE)
# })
scatter_bar_data=FALSE

```

```{rave build_analysis_data, language="R", export="analysis_data"}
# build a dataframe for each analysis type and (within trial grouping)
# and then rbind the result

# building the data frame basically means combining information from
# the settings and the trial-collapsed data

# first determine if there are any 0-trial groups
has_data <- which(sapply(analysis_groups, `[[`, 'has_trials'))

analysis_data <- list()
# analysis_data$data <- mapply(function(pp, nm) {
#   
#   sapply(pp, function(ppi) {
#     freq <- "FW" %&% str_collapse(ppi$settings$frequency, '_')
#     aw <- "AW" %&% str_collapse(ppi$settings$time, '_')
#     lbl <- ppi$settings$label
#     
#     data <- ppi$data$shifted_data_Fsub
#     
#     ##make sure the time dimension is 2
#     dm <- dimnames(data)
#     to_keep <- which.equal('Trial', names(dm))
#     
#     # make sure the time dimension is index 2
#     stopifnot(which.equal('Time', names(dm)) == 2 && which.equal('Electrode', names(dm)) == 4)
#     
#     t_ind <- as.numeric(dm$Time) %within% ppi$settings$time
#     
#     if(isTRUE(ppi$settings$censor_info$enabled)) {
#       t_ind = t_ind & !(
#         as.numeric(dm$Time) %within% ppi$settings$censor_info$window
#       )
#     }
#     
#     d <- ravetools::collapse(data[,t_ind,,,drop=FALSE], keep=3:4)
#     rep_numeric <- function(str, ...) rep(as.numeric(str), ...)
#     
#     df <- data.frame(
#       Trial_Group = nm,
#       Electrode = rep_numeric(dm$Electrode, each=nrow(d)),
#       Trial = rep_numeric(dm$Trial, times=ncol(d)),
#       Frequency = freq,
#       Window = aw,
#       Name = lbl,
#       y = c(d)
#     )
# 
#     df
#   }, simplify = FALSE, USE.NAMES = TRUE)
#   
# }, pluriform_power[has_data], names(pluriform_power)[has_data]) %>% rbind_list

# # set outlier column
# analysis_data$data$is_clean = TRUE
# if(length(trial_outliers_list)) {
#   analysis_data$data$is_clean[analysis_data$data$Trial %in% trial_outliers_list] = FALSE
# }

analysis_data$datatype <- baseline_settings$unit_of_analysis
```


```{rave build_over_time_by_electrode_dataframe, language='R', export='over_time_by_electrode_dataframe'}
over_time_by_electrode_dataframe <- NULL
# building data for the movie viewer
# first baseline all the electrodes
raveio::power_baseline(
  repository,
  baseline_windows = baseline_settings$window,
  method = get_unit_of_analysis(baseline_settings$unit_of_analysis),
  units = get_baseline_scope(baseline_settings$scope),
  signal_type = "LFP",
  electrodes = repository$electrode_list
)

# for each condition group and for each analysis setting
# get one value per TIME per electrode
non_empty_groups <- which(rutabaga::get_list_elements(
  analysis_groups, 'has_trials'))

combine_if_equal <- function(ll, nms = c('Electrode', 'Time')) {
  if(length(ll) == 1) {
    return(ll[[1]])
  }
  r1 <- ll[[1]]
  
  for(jj in seq_along(ll)[-1]) {
    
    stopifnot(all(
      dim(r1) == dim(ll[[jj]]),
      sapply(nms, function(nm) {
        all.equal(r1[[nm]], ll[[jj]][[nm]])
      })
    ))
  }
  r1
  for(jj in seq_along(ll)[-1]) {
    cn <- names(ll[[jj]])
    to_move = setdiff(cn, nms)
    
    r1[to_move] = ll[[jj]][to_move]
  }
  
  return(r1)
}

by_condition_group <-
  lapply(analysis_groups[non_empty_groups],
         function(ag) {
           res <- lapply(analysis_settings_clean, function(as) {
             # as = analysis_settings_clean[[1]]
             # freq needed
             fi <- repository$frequency %within% as$frequency
             
             # shift the data and subset on trials/freq
             p <- get_pluriform_power(
               baselined_data=repository$power$baselined[fi,,,,drop=FALSE],
               trial_indices = ag$trials, events = repository$epoch$table,
               epoch_event_types = get_available_events(repository$epoch$columns), trial_outliers_list=unlist(trial_outliers_list),
               event_of_interest = as$event, final_data_only=TRUE,
               sample_rate = repository$subject$power_sample_rate
             )
             
             # make sure dimensions are what we think they are
             stopifnot(
               names(dimnames(p)) == c('Frequency', 'Time', 'Trial', 'Electrode')
             )
             
             enames = as.integer(dimnames(p)$Electrode)
             times = as.numeric(dimnames(p)$Time)
             
             m <- ravetools::collapse(p[drop=FALSE], keep = c(4,2))
             
             df <- data.frame(
               reshape2::melt(m,
                              value.name=paste(sep='_', as$label, ag$label))
             )
             # head(df)
             names(df)[1:2] = c('Electrode', 'Time')
             df$Electrode = enames[df$Electrode]
             df$Time = times[df$Time]
             
             return(df)
           })
           
           # confirm everything lines up
           combine_if_equal(res)
         }
  )

#merge the resulting datasets
over_time_by_electrode_dataframe <- by_condition_group[[1]]

if(length(by_condition_group) > 1) {
  for(ii in seq_along(by_condition_group)[-1]){
    over_time_by_electrode_dataframe = merge(over_time_by_electrode_dataframe,
                                             by_condition_group[[ii]],
                                             all=TRUE)
  }
}

```

```{rave build_over_time_by_trial, language="R", export ="over_time_by_trial_data"}

build_data <- function(data, analysis_settings, condition_group, baseline_settings, ...) {
  
  dm <- dimnames(data)
  
  to_keep <- c(
    which.equal('Time', names(dm)),
    which.equal('Trial', names(dm))
  )
  
  res <- list(
    data = ravetools::collapse(data[,drop=FALSE], keep = to_keep),
    x = as.numeric(dm$Time),
    xlab='Time',
    ylab='Trial (sorted by condition)',
    zlab=sprintf('Mean %s', baseline_settings$unit_of_analysis)
  )
  
  res$range <- range(res$data)
  ind <- which(sapply(first_condition_groupings, `[[`, 'label')==condition_group[[1]])
  cnds <- first_condition_groupings[[ind]]$conditions
  
  tt = as.numeric(dm$Trial)
  res$y = trial_details[as.character(tt), 'Condition']
  cf <- factor(res$y, levels = cnds)
  ord = order(cf, tt)
  
  # sort the trial labels
  res$y <- res$y[ord]
  
  # NB: the condition data are stored in the COLUMNS of the data, so sort appropriately
  # this may feel odd, but this is because of how image(...) function works
  res$data <- res$data[,ord]
  
  return(res)
}

over_time_by_trial_data <- data_builder(
  pluriform_power, condition_groups = analysis_groups,
  baseline_settings = baseline_settings,
  BUILDER_FUN = build_data, 
  data_type = 'shifted_clean_data_Fsub'
)

```

```{rave build_omnibus_results, language="R", export="omnibus_results"}
# 
# first baseline all the electrodes
raveio::power_baseline(
  repository,
  baseline_windows = baseline_settings$window,
  method = get_unit_of_analysis(baseline_settings$unit_of_analysis),
  units = get_baseline_scope(baseline_settings$scope),
  signal_type = "LFP",
  electrodes = repository$electrode_list
)

# for each condition group and for each analysis setting
# get one value per trial per electrode
non_empty_groups <- which(rutabaga::get_list_elements(analysis_groups, 'has_trials'))
by_condition_group <- raveio::lapply_async(
  x = analysis_groups[non_empty_groups],
  function(ag) {
    lapply(analysis_settings_clean, function(as) {
      # freq needed
      fi <- repository$frequency %within% as$frequency
      
      # ei <- repository$electrode_list %in% ag$electrodes
      
      # shift the data and subset on trials/freq
      p <- get_pluriform_power(
        baselined_data=repository$power$baselined[fi,,,,drop=FALSE],
        trial_indices = ag$trials, events = repository$epoch$table,
        epoch_event_types = get_available_events(repository$epoch$columns), trial_outliers_list=unlist(trial_outliers_list),
        event_of_interest = as$event, final_data_only=TRUE,
        sample_rate = repository$subject$power_sample_rate
      )
      
      ti = as.numeric(dimnames(p)$Time) %within% as$time
      stopifnot(names(dimnames(p))[2] == 'Time')
      
      m <- ravetools::collapse(p[,ti,,,drop=FALSE], keep = 3:4)
      
      mse <- apply(m, 2, rutabaga::m_se)
      ts = mse[1,] / mse[2,]
      collapsed <- cbind(mse[1,],
                         ts,
                         2*pt(abs(ts), df = nrow(m)-1, lower.tail = F)
      )
      enames = dimnames(p)$Electrode
      rownames(collapsed) = enames
      colnames(collapsed) = paste0(c('m', 't', 'p'), '(', ag$label,   '; ', as$label, ')')
      
      by_trial <- data.frame(
        'y' = c(m),
        'Electrode' = rep(as.numeric(enames), each=nrow(m)),
        'Trial' = rep(ag$trials, times=ncol(m)),
        'Factor1' = ag$label,
        'Time' =  't' %&% str_collapse(as$time, '-'),
        'Freq' =  'f' %&% str_collapse(as$frequency, '-'),
        'Event' = as$event,
        'AnalysisLabel' = as$label
      )
      
      return(list('df' = by_trial, 'collapsed'=collapsed))
    })
  })

all_data <- rutabaga::rbind_list(sapply(by_condition_group, 
                              rutabaga::get_list_elements, 'df', use_sapply=FALSE))

# if we have a second factor (eventually an ROI) we need to clean up the naming
if(isTRUE(enable_second_condition_groupings)) {
  meta_table <- attr(analysis_groups, 'meta')
  
  stopifnot(is.data.frame(meta_table))
  
  all_data$Factor1 = NULL
  all_data %<>% merge(meta_table, by=c('Trial'))
  
  # add in an interaction factor
  all_data$Factor1Factor2 = mapply(paste, all_data$Factor1, all_data$Factor2, sep='.')
  
  # sort the levels
  all_data$Factor1Factor2 %<>% factor(levels = names(analysis_groups))
  
} else {
  if(!is.factor(all_data$Factor1)) {
    all_data$Factor1 %<>% factor(levels = names(by_condition_group))
  }
}

# make sure analysis label is appropriately factored
if(!is.null(all_data$AnalysisLabel)) {
  all_data$AnalysisLabel %<>% factor(levels = names(analysis_settings_clean))
}

# add in currently selected information so plots are accurate
# to selected electrodes
rn <- 'currently_selected'
while(rn %in% names(all_data)) {
  rn <- 'PWR_EXPLR_' %&% rn
}
all_data[[rn]] = all_data$Electrode %in% requested_electrodes

# collapsed_data <- cbind_list(sapply(by_condition_group, 
                                    # get_list_elements, 'collapsed', use_sapply=FALSE))

# for the stats, we need to figure out the factors involved and then build 
# the appropriate model
# for the post hocs, just get all pairwise for now. we'll need to have some
# kind of chooser for specific contrasts in the future (duplicate with group module)
get_factor_length <- function(x) length(unique(all_data[[x]]))
repeated_factors <- 'AnalysisLabel' #c('Time', 'Freq', 'Event')
unrepeated_factors <- c('Factor1', 'Factor2')
factor_lengths <- sapply(c(repeated_factors, unrepeated_factors), get_factor_length)
fixed_effects <- names(factor_lengths[factor_lengths>1])

formula_str <- paste0('y ~ ', str_collapse(fixed_effects, '*'))
if(formula_str == 'y ~ ') formula_str = 'y ~ 1' 

has_re <- any(repeated_factors %in% fixed_effects)
stat_fun <- stats::lm
if(has_re) {
  formula_str %<>% paste("+ (1|Trial)")
  stat_fun <- lmerTest::lmer
} 

run_stats <- function(el) {
  mod <- stat_fun(as.formula(formula_str), data=el)
  
  if(length(coef(mod)) == 1 && class(mod) != 'lmerModLmerTest') {
    lsm <- emmeans::emmeans(mod, specs = '1')
    summ <- summary(lsm, infer = TRUE)
    emm = matrix(unlist(t(summ[c('emmean', 't.ratio', 'p.value')])))
    lbls <- as.character(summ[[1]])
    
    rownames(emm) = c(outer(c('m(', 't(', 'p('),lbls, paste0)) %&% ')'
    
    res <- emm
  } else {
    lsm <- emmeans::emmeans(mod, as.formula('pairwise ~' %&% str_collapse(fixed_effects, '*')))
    summ <- summary(lsm$emmeans, infer = TRUE)
    emm = matrix(unlist(t(summ[c('emmean', 't.ratio', 'p.value')])))
    lbls <- apply(summ[,fixed_effects,drop=FALSE], 1, str_collapse, by=' ')
    
    rownames(emm) = c(outer(c('m(', 't(', 'p('),lbls, paste0)) %&% ')'
    
    cntr = summary(lsm, adjust='fdr')$contrasts
    cmat = matrix(unlist(t(cntr[,c('estimate','t.ratio', 'p.value')])))
    rownames(cmat) = c(t(sapply(c('m(', 't(', 'p_fdr('), paste0, cntr$contrast))) %&% ')'
    
    # get the overall results to add
    tmp <- summary(emmeans::emmeans(mod, specs='1'), infer=TRUE)
    tmp.emm = matrix(unlist(t(tmp[c('emmean', 't.ratio', 'p.value')])))
    tmp.lbls <- as.character(tmp[[1]])
    
    rownames(tmp.emm) = c(outer(c('m(', 't(', 'p('),tmp.lbls, paste0)) %&% ')'
    
    res <- rbind(tmp.emm, emm, cmat)
  }
  colnames(res) = el$Electrode[1]
  
  return(res)
}

# now we want to calculate the stats for each electrode
stats <- all_data %>% split((.)$Electrode) %>% 
  raveio::lapply_async(function(el) {
    tryCatch({
      return(run_stats(el))
    }, error = function(...) {
      # The data contains NA/NaN
      NULL
    })
  }) %>%
  rutabaga::cbind_list()

# add in "currently active" electrodes so users can filter
rn <- 'currently_selected'
while(rn %in% rownames(stats)) {
  rn = 'RAVE_' %&% rn
}
val = matrix(nrow=1,
             as.integer(colnames(stats) %in% as.character(requested_electrodes)),
             dimnames=list(rn))
stats %<>% rbind(val)

# add in electrode labels as an attribute of the stats block.
# don't add as row, otherwise we lose numeric-ness
attr(stats, 'electrode_labels') = repository$electrode_table$Label

#combine into large list for exporting
omnibus_results = list(
  # 'collapsed' = collapsed_data,
  'data' = all_data,
  'stats' = stats
)
```

```{rave build_data_for_export, language="R", export='data_for_export', cue = "always"}
warning("Overlapping time/frequency windows will not be coded properly in the export file")

if( getOption("knit_rave_pipelines", default = FALSE) ) {
  list2env(list("electrodes_to_export" = repository$power$dimnames$Electrode[1]), envir = environment())
}

prog <- shidashi::shiny_progress("Building export data", max=4, shiny_auto_close = TRUE)


data_for_export = FALSE

electrodes_to_keep <- dipsaus::parse_svec(electrodes_to_export, sep=',|;', connect  = ':-')
electrodes_to_keep %<>% remove_from_arr(repository$power$dimnames$Electrode, `%in%`, negate=TRUE)

## check for ROI exclusion criteria
if(electrodes_to_export_roi_name!='none') {
  v = if(electrodes_to_export_roi_name== 'Custom ROI') {
    
  } else {
    electrodes_to_export_roi_name
  }
  lbls <- subset(repository$electrode_table, Electrode %in% electrodes_to_keep, select=v, drop=TRUE)
  electrodes_to_keep = electrodes_to_keep[lbls %in% electrodes_to_export_roi_categories]
}

if(!length(electrodes_to_keep)){ 
  stop("No electrodes were found passing all selection criteria")
}

#
# FIXME 
# there might be efficiency wins if we subset trials NOW prior to baseline, but
# only if the baselines aren't already cached 

prog$inc("Baseline data [export loop]")
raveio::power_baseline(
  x = repository,
  baseline_windows = unlist(baseline_settings$window[[1]]),
  method = get_unit_of_analysis(baseline_settings$unit_of_analysis),
  units = get_baseline_scope(baseline_settings$scope),
  signal_type = "LFP",
  electrodes = electrodes_to_keep
)

prog$inc("Subset data")


# 
# first we work on the tensor (one per analysis setting,
# because of potential overlap), then flatten if requested at the end
#
tensors <- lapply(analysis_settings_clean, function(asc) {
  current_tensor = subset(repository$power$baselined, 
                          Electrode ~ Electrode %in% electrodes_to_keep)
  
  dn <- lapply(dimnames(current_tensor), as.numeric)
  
  # 
  # TRIAL DIMENSION
  tet <- trial_export_types()
  # first assume keeping all the trials
  trials_to_keep = repository$power$dimnames$Trial
  
  # if subset requested
  if(trials_to_export %in% c(tet$RAW_GRP, tet$CLP_GRP, tet$CLP_CND) ) {
    trials_to_keep <- unique(c(unlist(sapply(analysis_groups, `[[`, 'trials'))))
    ind <- dn$Trial %in% trials_to_keep
    current_tensor = current_tensor[,,ind,,drop=FALSE]
    dn$Trial <- as.numeric(dimnames(current_tensor)$Trial)
  }
  
  # do we need to collapse?
  if(trials_to_export == tet$CLP_GRP) {
    with_trials <- which_have_trials(analysis_groups)
    # note the sapply here to concat the result
    by_group <- sapply(analysis_groups[with_trials], function(ag) {
      ind <- (dn$Trial %in% ag$trials)
      ravetools::collapse(current_tensor[,,ind,,drop=FALSE], keep=c(1,2,4))
    })
    
    # this loses dimnames, so add them back
    current_tensor = tensor_reshape(mat = by_group, 
                                    orig_dim = dim(current_tensor), pivot=3)
    dn$Trial = unname(sapply(analysis_groups[with_trials], `[[`, 'label'))
    dimnames(current_tensor) = dn
  }
  
  # 
  # TIME DIMENSION
  tmet <- time_export_types()
  times_to_keep = repository$power$dimnames$Time
  # see if any time points can be dropped
  if(times_to_export %in% c(tmet$CLP_AWO, tmet$RAW_AWO)) {
    ind <- dn$Time %within% asc$time
    
    current_tensor = current_tensor[,ind,,,drop=FALSE]
    dn$Time = as.numeric(dimnames(current_tensor)$Time)
  }
  
  if(times_to_export == tmet$CLP_AWO) {
    tmp = ravetools::collapse(current_tensor, keep=c(1,3:4))
    
    dim(tmp) = c(dim(tmp), 1)
    
    # perm to put time dimension back in it's place
    current_tensor <- aperm(tmp, c(1,4,2,3))
    
    # all(0==range(current_tensor[,1,,] - tmp[,,,1]))
    dn$Time = asc$label
    dimnames(current_tensor) = dn
  }
  
  #
  # Frequency dimension
  fet = frequency_export_types()
  if(frequencies_to_export %in% c(fet$CLP_AWO, fet$RAW_AWO)) {
    ff <- dn$Frequency %within% asc$frequency
    current_tensor = current_tensor[ff,,,,drop=FALSE]
  }
  dn$Frequency = as.numeric(dimnames(current_tensor)$Frequency)
  
  if(frequencies_to_export == fet$CLP_AWO) {
    tmp = ravetools::collapse(current_tensor, keep = 2:4)
    dim(tmp) = c(dim(tmp),1)
    
    # perm to put time dimension back in it's place
    current_tensor <- aperm(tmp, c(4,1:3))
    # all(0==range(current_tensor[1,,,] - tmp[,,,1]))
    dn$Frequency = asc$label
    dimnames(current_tensor) = dn
  }
  
  return(current_tensor)
})

uoa = get_unit_of_analysis_varname(baseline_settings$unit_of_analysis)

if(electrode_export_data_type == 'tensor') {
  data_for_export =  mapply(function(tensor, asc) {
    dn <- dimnames(tensor)
    
    ## try to convert to numeric
    dn %<>% lapply(function(d) {
      nd <- suppressWarnings(as.numeric(d))
      if(any(is.na(nd))) return(d) 
      
      nd
    })
    
    res <- list(data=tensor)
    res[names(dn)] = dn
    
    res$unit = uoa
    
    res$baseline_window = baseline_settings$window[[1]]
    res$baseline_scope = baseline_settings$scope[[1]]
    
    return(res)
  }, tensors, analysis_settings_clean, SIMPLIFY = FALSE)
  
  names(data_for_export) = names(analysis_settings_clean)
  data_for_export$data_names=names(data_for_export)
  data_for_export$type='tensor_data'
  
} else {
  ## flattened data requested
  flat_tables <- mapply(function(tensor, asc) {
    tbl <- data.table::as.data.table(
      reshape2::melt(tensor[drop = FALSE], value.name = uoa)
    )
    tbl$AnalysisGroup = asc$label
    
    ###FIXME Add in meta data
    
    return(tbl)
    
  }, tensors, analysis_settings_clean, SIMPLIFY = FALSE)
  
  
  if(!data.table::is.data.table(flat_tables)) {
    # flat_tables %<>% rbind_list
    flat_tables <- rutabaga::rbind_list(flat_tables)
  }
  
  # convert factors back to characters
  flat_tables %<>% lapply(function(x) {
    if(is.factor(x)) {
      x <- as.character(x)
    }
    x
  }) %>% as.data.frame
  
  data_for_export = list(
    type='flat_data',
    data_names = 'all_data',
    all_data = list(data=flat_tables),
    metadata=list(
      unit = uoa,
      baseline_window = paste0(collapse=':', baseline_settings$window[[1]]), 
      baseline_scope = baseline_settings$scope[[1]]
    )
  )
}

```

```{r build, echo=FALSE, results='hide'}
build_pipeline(make_file = "make-power_explorer.R")
```

```{r visualize, echo=FALSE}
Sys.setenv("RAVE_PIPELINE" = normalizePath("."))
raveio::pipeline_visualize()
```
